version: "2"

services:

  web:
    build: "./web"
    ports:
      - "81:80"
    depends_on:
      - "api"

  api:
    build: "./api"
    expose:
      - "80"
    ports:
      - "82:80"
    depends_on:
      - "mongo"
      - "redis"

  worker:
    build: "./worker"
    depends_on:
      - "mongo"
      - "redis"

  redis:
    image: "redis:3.2.5"

  mongo:
    image: "mongo:3.2.11"
    expose:
      - "27017"