version: "2"

services:

  web:
    build: "./web"
    ports:
      - "80:80"
    # For development we compile the .ts
    # externally and map the volume.
    volumes:
      - "./web/html:/app"
    depends_on:
      - "api"

  api:
    build: "./api"
    expose:
      - "80"
    depends_on:
      - "mysql"
      - "redis"

  worker:
    build: "./worker"
    depends_on:
      - "mysql"
      - "redis"

  redis:
    image: "redis:3.2.5"
    expose:
      - "80"

  mysql:
    image: "mysql:5.7.16"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "fav_foods"
      MYSQL_DATABASE: "fav_foods"
      MYSQL_USER: "fav"
      MYSQL_PASSWORD: "foods"